spring:
  profiles:
    include: db
  datasource:
    url: ${mysql.url}  # 데이터베이스 URL
    username: ${mysql.username}                          # 사용자명
    password: ${mysql.password}                          # 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver          # MySQL JDBC 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: update                                   # 스키마 자동 업데이트 (생성/업데이트/없음 중 선택 가능)
    show-sql: true                                       # 실행되는 SQL 쿼리 로깅
    properties:
      hibernate:
        format_sql: true                                 # SQL 포맷팅